language: php

env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

php:
    - 5.4
    - 5.5

services:
    - mongodb

before_script:
    - phpenv config-add .travis.php.ini
    - cp config/parameters.yml.dist config/parameters.yml
    - composer dump-autoload
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST 

script: bin/phpunit
